/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.sql.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author AliCeleita
 */
public class Registrar extends javax.swing.JPanel {
public int doc1, edad1;
    public Timestamp fecSeg;
    public String nom1,ape1,dia,mes,año,fecNac;
    public LocalDate nac1;
    public Date nac2;
    private Persona per;
    
    public Registrar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labDoc = new javax.swing.JLabel();
        doc = new javax.swing.JTextField();
        labNom = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        labApe = new javax.swing.JLabel();
        ape = new javax.swing.JTextField();
        labEdad = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nac = new com.toedter.calendar.JDateChooser();
        url = new javax.swing.JTextField();
        exIm = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        reg = new javax.swing.JButton();
        bAg = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));

        labDoc.setText("Documento");

        labNom.setText("Nombre");

        labApe.setText("Apellido");

        labEdad.setText("Edad");

        jLabel1.setText("Fecha de nacimiento");

        url.setText("Direccion Imagen");

        exIm.setText("Examinar");
        exIm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exImActionPerformed(evt);
            }
        });

        reg.setText("Registrar");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });

        bAg.setText("Agregar");
        bAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labDoc)
                                    .addComponent(labNom)
                                    .addComponent(labApe)
                                    .addComponent(labEdad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(doc)
                                    .addComponent(nom)
                                    .addComponent(ape)
                                    .addComponent(edad, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exIm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bAg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(195, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reg)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labDoc)
                                .addComponent(doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(exIm)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labNom)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labApe)
                                    .addComponent(ape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labEdad)
                                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bAg)))
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(reg)
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        if(ape.getText().isEmpty()||doc.getText().isEmpty()||edad.getText().isEmpty()||nom.getText().isEmpty()||url.getText().isEmpty()||nac.getDate()==null||imagen.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Digite todos los datos");
        }else{
            try{
                doc1=Integer.parseInt(doc.getText());
                nom1=(String)nom.getText();
                ape1=(String)ape.getText();
                dia=Integer.toString(nac.getCalendar().get(Calendar.DAY_OF_MONTH));
                mes=Integer.toString((nac.getCalendar().get(Calendar.MONTH))+1);
                año=Integer.toString(nac.getCalendar().get(Calendar.YEAR));
                fecNac=dia+"/"+mes+"/"+año;
                nac1 = LocalDate.parse(fecNac, DateTimeFormatter.ofPattern("d/M/yyyy"));
                edad1=Integer.parseInt(edad.getText());
                LocalDateTime hoy=LocalDateTime.now();
                fecSeg=Timestamp.valueOf(hoy);
                nac2=Date.valueOf(nac1);
            }catch(NumberFormatException asd){
                JOptionPane.showMessageDialog(null,"Datos incorrectos");
            }
            switch(evt.getActionCommand())
            {
                case "Registrar":
                    
                    if(edad1>=5&&edad1<=15){
                        per=Persona.crear(0, doc1, nom1, ape1, edad1, nac2,fecSeg);
                        Repositorio.crear2(per);
                        JOptionPane.showMessageDialog(this, "Persona creada satisfactoriamente", "Bien", JOptionPane.INFORMATION_MESSAGE);
                    }else if(edad1>=16&&edad1<=24){
                        per=Persona.crear(0, doc1, nom1, ape1, edad1, nac2,fecSeg);
                        Repositorio.crear(per);
                        JOptionPane.showMessageDialog(this, "Persona creada satisfactoriamente", "Bien", JOptionPane.INFORMATION_MESSAGE);
                    }else if(edad1>=25&&edad1<=50){
                        per=Persona.crear(0, doc1, nom1, ape1, edad1, nac2,fecSeg);
                        Repositorio.crear3(per);
                        JOptionPane.showMessageDialog(this, "Persona creada satisfactoriamente", "Bien", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null,"Datos incorrectos, edad incorrecta");
                    }
                    
                    
                break;
                default:
                    JOptionPane.showMessageDialog(this, "Persona no creada", "mal", JOptionPane.INFORMATION_MESSAGE);
            }
            
            
        }
    }//GEN-LAST:event_regActionPerformed

    private void exImActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exImActionPerformed
        
	JFileChooser fc = new JFileChooser( "./data" );
	fc.setDialogTitle( "Buscar imagen de perro" );
	fc.setMultiSelectionEnabled( false );

	int resultado = fc.showOpenDialog( this );
        if( resultado == JFileChooser.APPROVE_OPTION ){
	    String imagen = fc.getSelectedFile( ).getAbsolutePath( );
	    url.setText( imagen);
        }
	 	
    }//GEN-LAST:event_exImActionPerformed

    private void bAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgActionPerformed
        String imagen = url.getText( );
	asignarimagen(imagen);
    }//GEN-LAST:event_bAgActionPerformed
    
    public void asignarimagen(String url) {
		
        ImageIcon icono = new ImageIcon();
            try {
                BufferedImage bImagen = ImageIO.read( new File( url ) );
                Image laImagen = bImagen.getScaledInstance( ( int ) ( 150 * 0.85 ), ( int ) ( 150 * 0.85 ), Image.SCALE_AREA_AVERAGING );;
                imagen.setIcon( new ImageIcon( laImagen ) );
            } catch (IOException e) {
                e.printStackTrace();
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape;
    private javax.swing.JButton bAg;
    private javax.swing.JTextField doc;
    private javax.swing.JTextField edad;
    private javax.swing.JButton exIm;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labApe;
    private javax.swing.JLabel labDoc;
    private javax.swing.JLabel labEdad;
    private javax.swing.JLabel labNom;
    private com.toedter.calendar.JDateChooser nac;
    private javax.swing.JTextField nom;
    private javax.swing.JButton reg;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables
}
