/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author AliCeleita
 */
public class Jugadores extends javax.swing.JFrame {
    //En este JFrame se manejan todos los paneles que contienen la informacion de los jugadores
    //registrados
    /**
     * Creates new form Jugadores
     */
    public Jugadores() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        registrar1 = new Clases.Registrar();
        mostrar1 = new Clases.Mostrar();
        juvenil1 = new Clases.Juvenil();
        adultos1 = new Clases.Adultos();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(600, 400));
        jTabbedPane1.addTab("Registro", registrar1);
        jTabbedPane1.addTab("Infantil", mostrar1);
        jTabbedPane1.addTab("Juvenil", juvenil1);
        jTabbedPane1.addTab("Adultos", adultos1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Clases.Adultos adultos1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private Clases.Juvenil juvenil1;
    private Clases.Mostrar mostrar1;
    private Clases.Registrar registrar1;
    // End of variables declaration//GEN-END:variables
}
